# Data Analytics Spring 2023 &mdash; Exercises 6

### Onni Roivas (last modified: Mon Apr 3 at 12:50)

- Five problems + round 5 peer review
- Round 5 peer review deadline: **Mon Apr 3 at 14:00**
- Problems deadline: **Tue Apr 11 at 14:00**
- Theme: classification
- **Make a copy of the original notebook** (right click & duplicate) and add your answers (new cells) there
- There may be no autosave
- **ALWAYS quit working by stopping the server [here](https://jupyter.vle.fi/home), then close your browser tabs**
- Please make both your code and your notebook readable
- When you are done, run the handin code cell at the end of this notebook
- The original notebook may change after publication, but the
  changes should be minor
- Keep your originals up to date by running the code cell below:

In [ ]:
import os
os.system('/usr/bin/bash /home/varpha/data_analytics/bin/config.sh');

## Round 5 peer review

**Deadline: Mon Apr 3 at 14:00**. Nothing new here!

In case you handed in your round 05 exercises, your folder **private/exrc_05/peer_review** should contain an anonymous round 05 solutions notebook of another student. In addition, some model solutions for round 05 are to be found in the folder **public/model_solutions**.

Write a few paragraphs of text (plain or markdown) into your favourite text editor and submit by running the code cell below. Please address the following issues:
 
- Are the solutions okay? Can you understand / run the code?<br/>
- What do you think about the solutions?
- How many points out of 5 do they deserve as a whole?
- How many points would you give to yourself and why?
- Any feedback or comments to Harri?

Harri will read and grade your reviews as follows:
- nonexistent or nearly so = 0p
- something written = 1-2p
- well written 3p.

When done with writing your review, please run the code cell below. It asks you to copy-paste your review text to a field that will become visible once you run the cell.


In [ ]:
import sys
sys.path.append('/home/varpha/data_analytics/lib')
from handin import submit_peer_review
submit_peer_review()

You may double check your review submission by running the following in the terminal (copy-paste & press enter):

> **cat /home/varpha/data_analytics/private/AB0410/exrc_05/peer_review/review_by_AB0410.txt**


### Problem 1. Wines


[Here](https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p01_wine.csv) is some data on Portuguese wines. 

Drop rows with missing values.

Use logistic regression to predict the type (white/red) from the other fields.

Split train/test set 70/30 %. Print the score and the confusion matrix.


In [5]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

df = pd.read_csv('https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p01_wine.csv')


# drop rows with empty values
df = df.dropna()

X = df.drop(['type'], axis=1)
y = df['type']

# test size 30% with random seed of 42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# use liblinear solver here
model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print('Score:', accuracy_score(y_test, y_pred))
print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))
print('\n Within this matrix, the first row represents white wines and second row red wines.')
print('\n There are 458 True Positives for white wines and 1451 True Positives for red wines.\n There are 19 False positives for white wines and 11 False Positives for red wines.')

Score: 0.9845281072717896
Confusion matrix:
 [[ 458   19]
 [  11 1451]]

 Within this matrix, the first row represents white wines and second row red wines.

 There are 458 True Positives for white wines and 1451 True Positives for red wines.
 There are 19 False positives for white wines and 11 False Positives for red wines.


### Problem 2. Voices
[Here](https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p02_voice.csv) is some data on human voices ([column info](https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p02_voice.txt)).
 
Predict the label from the other fields using a support vector machine.

Split train/test set 70/30 %.

Print the score and the confusion matrix.


In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv('https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p02_voice.csv')

# test size 30% with random seed of 42
X = df.drop('label', axis=1)
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# scaling data, StandardScaler to make sure that all features have equal importance in the svm model
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# support vector machin model
clf = SVC(kernel='linear')
clf.fit(X_train, y_train)

# evaluate the model on the test data
y_pred = clf.predict(X_test)
score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

# results
print('Accuracy Score:', score)
print('Confusion Matrix:')
print(cm)
print('same matrix structure as last exercise')
print('\n There are 437 correctly classified male voices \n There are 486 correctly classified female voices \n There are 15 misclassified male voices \n There are 13 misclassified female voices')

Accuracy Score: 0.9705573080967402
Confusion Matrix:
[[437  15]
 [ 13 486]]
same matrix representation as last exercise

 There are 437 correctly classified male voices 
 There are 486 correctly classified female voices 
 There are 15 misclassified male voices 
 There are 13 misclassified female voices


### Problem 3. NBA
[Here](https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p03_nba.csv) is some data on NBA basketball players in their first season ([column info](https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p03_nba.csv)).

Last column tells if player's career has exceed 5 years or not.

Fill missing values with the field median.

Try to predict if the career has exceeded 5 years or not by using both logistic regression and a support vector machine. Print scores and confusion matrices. Split train/test data as you wish. Compare the results.


In [19]:
import pandas as pd
df = pd.read_csv('https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p03_nba.csv')

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Name'] = le.fit_transform(df['Name'])

# Replace missing values with median
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='median')
df = pd.DataFrame(imp.fit_transform(df), columns=df.columns)

# Preprocessing the data
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Splitting the data 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# logistic regression model
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=0, max_iter=5000)
lr.fit(X_train, y_train)

# Predictions and print scores and confusion matrix for logistic regression
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred_lr = lr.predict(X_test)
print('Logistic Regression Accuracy:', accuracy_score(y_test, y_pred_lr))
print('Logistic Regression Confusion Matrix:\n', confusion_matrix(y_test, y_pred_lr))

# Support vector machine model
from sklearn.svm import SVC
svm = SVC(kernel='linear', random_state=0)
svm.fit(X_train, y_train)

# Predictions
y_pred_svm = svm.predict(X_test)
print('Support Vector Machine Accuracy:', accuracy_score(y_test, y_pred_svm))
print('Support Vector Machine Confusion Matrix:\n', confusion_matrix(y_test, y_pred_svm))
print('\nFrom the first confusion matrix, we can see the following:')
print('There are 61 True Negatives which means players whose careers never went past 5 years and were classified correctly')
print('There are 126 True Positivies which means players whose careers went past 5 years and were classified correctly')
print('There are 57 False Negatives which means which means players whose careers went past 5 years but were incrroctly classified')
print('There are 24 False positivies which means players whose careers went past 5 years but were incorrectly classified')

print('\nFrom the second confusion matrix, we can see the following:')
print('There are 64 True Negatives which means players whose careers never went past 5 years and were classified correctly')
print('There are 125 True Positivies which means players whose careers went past 5 years and were classified correctly')
print('There are 54 False Negatives which means which means players whose careers went past 5 years but were incrroctly classified')
print('There are 25 False positivies which means players whose careers went past 5 years but were incorrectly classified')

Logistic Regression Accuracy: 0.6977611940298507
Logistic Regression Confusion Matrix:
 [[ 61  57]
 [ 24 126]]
Support Vector Machine Accuracy: 0.7052238805970149
Support Vector Machine Confusion Matrix:
 [[ 64  54]
 [ 25 125]]

From the first confusion matrix, we can see the following:
There are 61 True Negatives which means players whose careers never went past 5 years and were classified correctly
There are 126 True Positivies which means players whose careers went past 5 years and were classified correctly
There are 57 False Negatives which means which means players whose careers went past 5 years but were incrroctly classified
There are 24 False positivies which means players whose careers went past 5 years but were incorrectly classified

From the second confusion matrix, we can see the following:
There are 64 True Negatives which means players whose careers never went past 5 years and were classified correctly
There are 125 True Positivies which means players whose careers went 

### Problem 4.  Mushrooms
[Here](https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p04_mushrooms.csv) is some data on mushrooms ([column info](https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p04_mushrooms.txt)).

Try to predict the class (edible or poisonous) from the other fields. Use whatever you want!

Fields are categorial so one-hot-encoding is needed.


In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from xgboost import XGBClassifier

data = pd.read_csv('https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p04_mushrooms.csv')

# encoding the variable as binary (0 for 'e' and 1 for 'p')
le = LabelEncoder()
y = le.fit_transform(data['class'])

# splitting into features and target
X = data.drop('class', axis=1)
# one-hot-encode
X = pd.get_dummies(X)

# splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# EXB technique is taking weak models and creates one single model
model = XGBClassifier()
model.fit(X_train, y_train)

# model the accuracy
accuracy = model.score(X_test, y_test)
print('Accuracy:', accuracy)
print('XGBoost predicted entire class of all mushrooms correct with 30% test size')

Accuracy: 1.0
XGBoost predicted entire class of all mushrooms correct with 30% test size


### Problem 5. Loan status
[Here](https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p05_loan.txt) is some data on loanees. Last column Loan_Status Y/N, should be predicted from the other field. Use whatever you want.  


Do modifications:
* Categorial fields to numeric (2-value fields to 0/1, multivalue as dummies)
* replace missing values with median
* remove rows with outliers: ApplicantIncome, CoapplicantIncome or LoanAmount over 3 standard deviations away from field average


Check what would be model's probability to Loan_status = Yes with values:

```
Gender                   Male
Married                    No
Dependents                  0
Education            Graduate
Self_Employed              No
ApplicantIncome          2400
CoapplicantIncome        2000
LoanAmount                 36
Loan_Amount_Term          360
Credit_History              1
Property_Area           Urban
```

In [39]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer

df = pd.read_csv('https://student.labranet.jamk.fi/~varpha/data_analytics/exrc06p05_loan.txt', delimiter=',')
df.dropna(inplace=True) # remove NaNs

# categorical features to numeric
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})
df['Married'] = df['Married'].map({'Yes': 1, 'No': 0})
df['Education'] = df['Education'].map({'Graduate': 1, 'Not Graduate': 0})
df['Self_Employed'] = df['Self_Employed'].map({'Yes': 1, 'No': 0})

# dummy variables for Property_Area
property_area_dummies = pd.get_dummies(df['Property_Area'], prefix='Property_Area')

# new columns to the dataframe
df = pd.concat([df, property_area_dummies], axis=1)

# Property_Area column
df.drop('Property_Area', axis=1, inplace=True)

# imputer object with median strategy
imputer = SimpleImputer(strategy='median')

# Replace missing values with median
df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median(), inplace=True)
df['Credit_History'].fillna(df['Credit_History'].median(), inplace=True)

# remove the specified outliers
df = df[(np.abs(stats.zscore(df[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount']])) < 3).all(axis=1)]

# split data into training and testing sets and use test size 30%
X = df.drop(columns=['Loan_ID', 'Loan_Status'])
y = df['Loan_Status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# logistic regression model
clf = LogisticRegression(random_state=42, solver='lbfgs', max_iter=1000).fit(X_train, y_train)

# predictions on testing set and calculate accuracy
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# prediction for input data
input_data = {'Gender': 1,
              'Married': 0,
              'Dependents': 0,
              'Education': 1,
              'Self_Employed': 0,
              'ApplicantIncome': 2400,
              'CoapplicantIncome': 2000,
              'LoanAmount': 36,
              'Loan_Amount_Term': 360,
              'Credit_History': 1,
              'Property_Area_Rural': 0,
              'Property_Area_Semiurban': 0,
              'Property_Area_Urban': 1}

# input data into dataframe
input_df = pd.DataFrame.from_records([input_data])

# prediction and get probability of Loan_Status = Yes
prob = clf.predict_proba(input_df)[:, 1][0]
print(f'Probability of Loan_Status = Yes: {prob}')
print('\nAccuracy means the status of the approval is around 87,44% based on the dataset')
print('Probability of Loan_status means that there is 88,18% chance for loan to be approved')

Accuracy: 0.874439461883408
Probability of Loan_Status = Yes: 0.8817631530288667

Accuracy means the status of the approval is around 87,44% based on the dataset
Probability of Loan_status means that there is 88,18% chance for loan to be approved


## Handin your final answers by running the code cell below.
- Save your latest changes.
- Please remove anything that may identify you to your anonymous reviewer. See [this Teams message](https://teams.microsoft.com/l/message/19:wpZLQbHG775XujahAR4ScrnPZGiByh6yuWgewJCHXVQ1@thread.tacv2/1675678597453?tenantId=6e9eaaf0-3ff7-4de9-8cd4-1ffbd45951b9&groupId=ba0bbd60-8a1b-42b8-84ff-6de6a3c45ab6&parentMessageId=1675678597453&teamName=Data%20Analytics%20YAMK%2C%20Spring%202023&channelName=General&createdTime=1675678597453&allowXTenantAccess=false).
- You may run the code cell as many times as you wish.
- Your permission to write the handin file ends at the deadline.

In [40]:
import sys
sys.path.append('/home/varpha/data_analytics/lib')
from handin import handin_exrc_06
handin_exrc_06()


All the relevant .ipynb files in your current directory:

  1. exrc_06-Copy1.ipynb



Please input the order number (the one in the beginning of the line) of the file you want to hand in:  1



Your answers to the first exercises were handed in successfully. Thank you!
You may double check your handin by calling

    /home/varpha/data_analytics/bin/handin.sh

from the terminal prompt.
